### PR TITLE
This is the pull request to fix the Hoshi bug as discussed in issue #33

### PR DESCRIPTION
**Pull request by dilizarov**
https://github.com/raulriera/TextFieldEffects/issues/33

### CODE REVIEW

**Comment by raulriera** [comment]
Thank you for this!, simplified a bit the effect instead

**Comment by dilizarov** [comment]
@raulriera I tried your latest fix in your demo, and if you again, try to clear very fast, sometimes the placeholder just disappears and sometimes the background color changes. I don't think the background color change is an issue. Probably just demo based, but idk about the placeholder disappearing.

**Comment by raulriera** [comment]
Really? I tried hitting tab really quickly and I didn't see an issue... On the background, if it turns gray is because that is the cell background and not the textfield 😅

**Comment by raulriera** [comment]
I can't replicate the issue... and this is pretty fast
hoshi

**Comment by dilizarov** [comment]
@raulriera Yeah, I figured that what the issue with the background, and on my device I would continuously switch between the two fields very, very quickly and it'd happen. Odd that it doesn't for you.

**Pull request closed without merging**
