### PR TITLE
add Juro

### PR DESCRIPTION
**Pull request by hotogwc**

### CODE REVIEW

**Comment by raulriera** [comment]
This looks amazing, just a minor whitespace fixes that I will change once I am able to test it :( right now Xcode 6 is broken on my mac (El Capitan broke it, keep crashing when I open Xcode, will check it out soon :) thanks!

**Comment by hotogwc** [comment]
you mean the whitespace between two JuroTextFields? I changed the constraints on purpose as they will  stick together if I didn't, so they look a little bit inconsistent with others.

**Comment by raulriera** [comment]
No, I meant the whitespace in the code :)

**Comment by hotogwc** [comment]
Ah OK,kind of bad code habit. Sorry for that. Actually I'm working on Nao and will eliminate the whitespace:)

**Comment by raulriera** [comment]
Just tested out, pretty sweet... just 2 small problems :( 

screen shot 2015-08-07 at 10 29 49
The cursor indicator looks like it's positioned incorrectly

And finally, when you rotate the device the text disappears and only appears again when I touch it :(

**Comment by hotogwc** [comment]
Got it! Try to fix them in weekend

**Comment by hotogwc** [comment]
Sorry, committed wrongly. Will rollback

**Comment by raulriera** [comment]
Oouuuu `Nao`, exciting :D but yeah, make it it's own pull request :)

**Comment by mukyasa** [comment]
Hello @raulriera @hotogwc  added some more effects also Juro,Do share ur feedback
https://github.com/mukyasa/MMTextFieldEffects

**Comment by raulriera** [comment]
Looking pretty nice, awesome work @mukyasa Too bad they are not in Swift to incorporate them in this repo :(

**Comment by raulriera** [comment]
Closing this it's been a while, feel free to reopen it when you have updated the pull request :)

**Pull request closed without merging**
