### PR TITLE
yoshiko fix for background color

### PR DESCRIPTION
**Pull request by spotby**
when border color is set, the color of the background is set to the color of the border . I think this is probably a mistake.

### CODE REVIEW

**Comment by raulriera** [comment]
This is on purpose, so the inactive and active colors are the ones controlling the design. Otherwise white will be hardcoded

**Comment by spotby** [comment]
well, the problem was that it was setting the background color to the *border* color, not the background color.  I added the white in there as a default, feel free to take that out.  this is what I'm trying to achieve (rendered with my fix)  before the fix the background was all white if I set the border color to white.:
image

**Comment by raulriera** [comment]
Yeah, that is the intended behavior for Yoshiko, it is not supposed to look like you have it on your screenshot (a visible border around the inactive field).

a

Check out in the example (and the website with the HTML versions where the inspiration came from) it goes from no border to a colorful border when selected

**Comment by raulriera** [comment]
Closing as this is the intended effect. Thanks for the PR though!

**Pull request closed without merging**
