### PR TITLE
Update TextFieldEffects.swift

### PR DESCRIPTION
**Pull request by hyerra**
Fixes issues to build with Swift 4

### CODE REVIEW

**Comment by raulriera** [comment]
Thanks! but the project will also need to be updated to Xcode9. I am currently waiting to be out of beta before pushing xcode9 changes

**Comment by hyerra** [comment]
Good point! Do you think it’d be a good idea to make a swift 4/Xcode 9 branch?

**Comment by raulriera** [comment]
Yeah, that would be nice!

**Comment by hyerra** [comment]
Sounds great! Could you make a swift 4 branch and I'll rebase to that branch?

**Comment by raulriera** [comment]
Done 👌

**Comment by hyerra** [comment]
Awesome! I rebased :)

**Pull request merged**
