### PR TITLE
Position problems with RightView, LeftView and ClearView

### PR DESCRIPTION
**Pull request by josechagas**
-Solving problems when working with clearView,rightView and leftView.
Specifically when using these features  together or not we have problems with position of typed             text, placeholder text and with the added views, like related on issue #125 

-Updating demo project to present the updates.

Solving Issues:
#125 
#82

### CODE REVIEW

**Comment by raulriera** [comment]
Seems to work pretty good! thanks. I need to clean up the comments and different code style before making a new version.

**Comment by PedroAlcaide** [comment]
This is still working?? I can't access this functions in my code, in the last version ( 1.4.0 ) from TextFieldsEffects.
Do you have any ideia when you will implements this?

**Comment by raulriera** [comment]
> This is still working?? I can't access this functions in my code, in the last version ( 1.4.0 ) from TextFieldsEffects.

Hi, can you be more specific? What functions?

**Comment by PedroAlcaide** [comment]
> Hi, can you be more specific? What functions?

Hi, I'm trying to set leftView but doesn't work. I saw this Issue and I try to use this function "repositionLeftView", but it doesn't exists. How can I use the solution gave by joseChagas?

**Comment by raulriera** [comment]
This code was never merged, you will need to use his branch directly

**Pull request closed without merging**
